name: 27-lint

on:
  push:
    branches: [ main ]
    paths:
      - src/**
  pull_request:
    branches: [ main ] 
    paths:
      - src/**

jobs:

  lint:
    runs-on: ubuntu-latest
    name: Lint con Flake 8
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
